### ISSUE TITLE
Add PTZ for Yi home some with Yi hack

### ISSUE THREAD

**Issue by skylarhays** [roleoroleo/yi-hack_ha_integration#165]
The documentation is pretty sparse on adding PTZ
Controls. I tried adding the blurb in the docs for the left button to the config yaml and got nothingb. Any help would be appreciated.

Sorry posted iPhone. Subject should say Yi home dome

**Comment by roleoroleo** [comment]
This is my card:
```
camera_view: auto
camera_image: camera.yi_hack_a2_xxxxxx_cam
entities:
  - entity: switch.switch_cam_kitchen_left
    icon: mdi:arrow-left-bold-circle-outline
  - entity: switch.switch_cam_kitchen_up
    icon: mdi:arrow-up-bold-circle-outline
  - entity: switch.switch_cam_kitchen_down
    icon: mdi:arrow-down-bold-circle-outline
  - entity: switch.switch_cam_kitchen_right
    icon: mdi:arrow-right-bold-circle-outline
  - entity: light.luce_kitchen
tap_action:
  action: url
  url_path: rtsp://192.168.1.200/ch0_0.h264
title: kitchen
type: picture-glance
```

**Comment by skylarhays** [comment]
You manually add that to the configuration.yaml?

**Comment by skylarhays** [comment]
these are the switches I see under the entities for yi-hack

yi_hack_m_88972b Baby Crying
binary_sensor.yi_hack_m_88972b_baby_crying
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Baby Crying Detect
switch.yi_hack_m_88972b_baby_crying_detect
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Cam
camera.yi_hack_m_88972b_cam
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Cruise
select.yi_hack_m_88972b_cruise
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b IR
switch.yi_hack_m_88972b_ir
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b LED
switch.yi_hack_m_88972b_led
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Media Player
media_player.yi_hack_m_88972b_media_player
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Motion Detection
binary_sensor.yi_hack_m_88972b_motion_detection
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Motion Detection Cam
camera.yi_hack_m_88972b_motion_detection_cam
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Rotate
switch.yi_hack_m_88972b_rotate
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Save Video on Motion
switch.yi_hack_m_88972b_save_video_on_motion
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Sensitivity
select.yi_hack_m_88972b_sensitivity
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Sound Sensitivity
select.yi_hack_m_88972b_sound_sensitivity
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Status
binary_sensor.yi_hack_m_88972b_status
Yi Cam with yi-hack
Aquarium
—
yi_hack_m_88972b Switch On
switch.yi_hack_m_88972b_switch_on
Yi Cam with yi-hack
Aquarium

**Comment by skylarhays** [comment]
Sorry... I see the code edit on the cards now... Are you creating a card for the PTZ seperately or editing an existing?

**Comment by roleoroleo** [comment]
> Sorry... I see the code edit on the cards now... Are you creating a card for the PTZ seperately or editing an existing?

I created a new card with image and buttons.

> On my switches I dont see right, left, up, and down... should they be there or do you have to create them?

You have to create the switches as described in the readme.
https://github.com/roleoroleo/yi-hack_ha_integration?tab=readme-ov-file#add-ptz-buttons-to-dashboard-only-if-supported-by-the-camera

**Comment by skylarhays** [comment]
Thanks for the reply Im able to do a single button per card like this and it works. I had to create 4. One for each direction. Is there a way to put these all on one card. and Im confused how you overlaid on the image.

show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: yi_hack.ptz
  target: {}
  data:
    movement: left
    entity_id: camera.yi_hack_m_88972b_cam
icon: mdi:arrow-left-bold-circle-outline
name: yicam_ptz_left
entity: camera.yi_hack_m_88972b_cam
show_state: false
icon_height: 50px


If i try to add multiple buttons on single it gives me an error. How did you create entities from the switches? so you were able to overlay the icons on the image? I tried modifying your settings but realize i dont have them set up as entities and the readme really doesnt cover that. Sorry really noobish on code stuff but trying to learn for the sake of HA

**Comment by roleoroleo** [comment]
> One for each direction. Is there a way to put these all on one card?

My example above contains 5 buttons.

First you have to create the buttons in your yaml:
```
type: button
tap_action:
  action: call-service
  service: yi_hack.ptz
  target: {}
  data:
    movement: left
    entity_id: camera.yi_hack_v5_abb....
icon: mdi:arrow-left-bold-circle-outline
name: yicam_ptz_left
```
Then you have to create the card in lovelace.
