### ISSUE TITLE
How to get snaphot from motion detection?

### ISSUE THREAD

**Issue by bit111** [roleoroleo/yi-hack_ha_integration#166]
Hello,
I've integrated a Yi Dome 1080p in Home Assistant. 
I noticed that when a motion is detected, a snapshot is saved and accessible via `camera.yi_camera_name_motion_detection_image`.

If I click on this "Motion Detection" sensor a popup with "Download Snapshot" button is displayed like the following:
<img width="212" alt="Image" src="https://github.com/user-attachments/assets/a627aafe-4476-4eed-99d4-4d3f55cab326" />

Is there a way to get this saved snapshot?

This is my automation:
```yaml
triggers:
  - type: motion
    device_id: xxxxxxx
    entity_id: yyyyyyyy
    domain: binary_sensor
    trigger: device
actions:
  - action: notify.me
    metadata: {}
    data:
      message: Movement detected!
      data:
        photo:
          - file: /api/camera_proxy/camera.yi_camera_name_motion_detection_image
            caption: Movement detected!
mode: single
```

but no message is sent and in HA logs I have these error:

```
home-assistant  | 2025-03-09 WARNING (MainThread) [homeassistant.components.telegram_bot] '/api/camera_proxy/camera.yi_camera_name_motion_detection_image' are not secure to load data from!
home-assistant  | 2025-03-09 ERROR (MainThread) [homeassistant.components.telegram_bot] Can't send file with kwargs: {'message': "Movement detected", 'file': '/api/camera_proxy/camera.yi_camera_name_motion_detection_image', 'caption': 'Movement detected'}
```
