### ISSUE TITLE
PTZ presets

### ISSUE THREAD

**Issue by Meow-ops** [roleoroleo/yi-hack_ha_integration#168]
Is there a way to add a card or an automation to make the camera go to a preset position like with ```http://mycameraip.com/cgi-bin/preset.sh?action=go_preset&num=0```

**Comment by roleoroleo** [comment]
It's already available.
Check the service move_to_preset

**Comment by Meow-ops** [comment]
alright! It works really well,
Here is the tile configuration I used if anyone else needs it:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: yi_hack.move_to_preset
  target: {}
  data:
    preset_id: 1
    entity_id: camera.yi_hack_a2_..._cam
icon: mdi:alarm-light
name: yicam_ptz_preset
show_state: true
```
